/**
 * WebMCP Compiled Tools Registry
 *
 * This file is AUTO-GENERATED by vite-plugin-webmcp-compiler.
 * DO NOT EDIT manually - changes will be overwritten on next build.
 *
 * Registry of pre-compiled tools with metadata for lifecycle injection.
 * Tools are compiled to static files that bypass CSP via chrome.scripting files:[].
 */

export interface CompiledToolInfo {
  id: string; // Full tool ID: namespace_name
  file: string; // Relative path from dist: tools/agentboard_page_info.js
  match: string[]; // URL patterns to match for injection
  version: string; // Tool version
  description: string; // Tool description for UI display
}

/**
 * Array of all compiled tools
 * Used by lifecycle.ts to determine which tools to inject into each tab
 */
export const COMPILED_TOOLS: CompiledToolInfo[] = [
  {
    id: 'agentboard_get_full_page_context',
    file: 'tools/agentboard_get_full_page_context.js',
    match: ['<all_urls>'],
    version: '3.0.0',
    description:
      'Get full page context beyond the default <page_context>. Returns comprehensive metadata and, where possible, page content extracted as clean markdown. Use when URL/title from <page_context> is insufficient.',
  },
  {
    id: 'agentboard_youtube_transcript',
    file: 'tools/agentboard_youtube_transcript.js',
    match: ['*://www.youtube.com/watch*', '*://youtube.com/watch*'],
    version: '1.0.0',
    description:
      'Extract transcript and metadata from the current YouTube video. Returns title, author, duration, description, view count, and full transcript with timestamps.',
  },
];
