/**
 * WebMCP Compiled Tools Registry
 *
 * This file is AUTO-GENERATED by vite-plugin-webmcp-compiler.
 * DO NOT EDIT manually - changes will be overwritten on next build.
 *
 * Registry of pre-compiled tools with metadata for lifecycle injection.
 * Tools are compiled to static files that bypass CSP via chrome.scripting files:[].
 */

export interface CompiledToolInfo {
  id: string; // Full tool ID: namespace_name
  file: string; // Relative path from dist: tools/agentboard_page_info.js
  match: string[]; // URL patterns to match for injection
  version: string; // Tool version
  description: string; // Tool description for UI display
}

/**
 * Array of all compiled tools
 * Used by lifecycle.ts to determine which tools to inject into each tab
 */
export const COMPILED_TOOLS: CompiledToolInfo[] = [
  {
    id: 'agentboard_dom_query',
    file: 'tools/agentboard_dom_query.js',
    match: ['<all_urls>'],
    version: '1.0.0',
    description: 'Extract DOM elements from current tab using CSS selectors.',
  },
  {
    id: 'agentboard_dom_readability',
    file: 'tools/agentboard_dom_readability.js',
    match: ['<all_urls>'],
    version: '2.1.0',
    description:
      'Extract readable content from current tab: metadata such as title, author, published time, etc; markdown content presented to the user.',
  },
  {
    id: 'agentboard_page_info',
    file: 'tools/agentboard_page_info.js',
    match: ['<all_urls>'],
    version: '1.0.0',
    description: 'Extract metadata, title, and Open Graph tags from current tab.',
  },
  {
    id: 'agentboard_shopify_bootstrap',
    file: 'tools/agentboard_shopify_bootstrap.js',
    match: ['<all_urls>'],
    version: '1.0.0',
    description:
      'Dynamically discovers and registers Shopify MCP tools for searching merchant catalog and managing cart.',
  },
  {
    id: 'agentboard_youtube_transcript',
    file: 'tools/agentboard_youtube_transcript.js',
    match: ['*://www.youtube.com/watch*', '*://youtube.com/watch*'],
    version: '1.0.0',
    description: 'Extract transcript/captions and metadata from current YouTube video.',
  },
];
