/** Type mirror for the injected JavaScript module; keep synchronized with script.js. */
export interface YouTubeTranscriptArguments {
  language?: string;
  format?: 'segments' | 'text';
}

export interface YouTubeTranscriptResult {
  metadata: {
    videoId: string;
    title: string;
    author: string;
    channelId: string;
    lengthSeconds: number;
    viewCount: number;
    description: string;
    keywords: string[];
    isLive: boolean;
  };
  transcript: null | {
    language: string;
    languageName: string;
    isAutoGenerated: boolean;
    segmentCount: number;
    text?: string;
    segments?: Array<{ start: number; duration: number; text: string }>;
  };
  error?: string;
}

export interface YouTubeTranscriptExecutionOptions {
  signal?: AbortSignal;
}

export function execute(
  args?: YouTubeTranscriptArguments,
  options?: YouTubeTranscriptExecutionOptions
): Promise<YouTubeTranscriptResult>;
