/**
 * Built-in Tool Sources Bundle
 *
 * This file is AUTO-GENERATED by vite-plugin-webmcp-compiler.
 * DO NOT EDIT manually - changes will be overwritten on next build.
 *
 * Contains self-contained source code for built-in page tools.
 * Used by Options UI to display read-only source code for learning/reference.
 */

export const BUILTIN_SOURCES: Record<string, string> = {
  agentboard_youtube_transcript: `'use webmcp-tool v1';

const YOUTUBE_ORIGIN = 'https://www.youtube.com';
const TRANSCRIPT_PANEL_TARGET = 'engagement-panel-searchable-transcript';
const TRANSCRIPT_LOAD_TIMEOUT_MS = 5_000;
const TRANSCRIPT_CANCEL_CLEANUP_TIMEOUT_MS = 500;

let transcriptPanelLoad = null;

export const metadata = {
  name: 'youtube_transcript',
  namespace: 'agentboard',
  version: '1.0.2',
  description:
    "Get the current YouTube video's transcript with timestamps and metadata. Retrieval may briefly open and close YouTube's transcript panel.",
  match: ['*://www.youtube.com/watch*', '*://youtube.com/watch*'],
  inputSchema: {
    type: 'object',
    properties: {
      language: {
        type: 'string',
        description:
          'Preferred language code (e.g., "en", "es"). Defaults to English or first available.',
      },
      format: {
        type: 'string',
        enum: ['segments', 'text'],
        description:
          '"segments" returns timestamped array, "text" returns concatenated plain text. Default: "segments"',
      },
    },
    additionalProperties: false,
  },
};

export async function execute(args = {}, { signal } = {}) {
  signal?.throwIfAborted();
  const videoId = currentVideoId();
  if (!videoId) {
    throw new Error('Not on a YouTube video page (no video ID found)');
  }

  const playerResponse = resolvePlayerResponse(videoId);
  const videoDetails = playerResponse.videoDetails || {};
  const metadata = {
    videoId,
    title: videoDetails.title || '',
    author: videoDetails.author || '',
    channelId: videoDetails.channelId || '',
    lengthSeconds: parseInt(videoDetails.lengthSeconds, 10) || 0,
    viewCount: parseInt(videoDetails.viewCount, 10) || 0,
    description: videoDetails.shortDescription || '',
    keywords: videoDetails.keywords || [],
    isLive: videoDetails.isLiveContent || false,
  };

  const captionTracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!captionTracks?.length) {
    return {
      metadata,
      transcript: null,
      error: 'No captions available for this video',
    };
  }

  // Prefer manual captions over auto-generated (ASR) captions.
  const manualTracks = captionTracks.filter((track) => !track.kind);
  const tracksToSearch = manualTracks.length > 0 ? manualTracks : captionTracks;
  const preferredLanguage = args.language || 'en';
  const selectedTrack =
    tracksToSearch.find((track) => track.languageCode === preferredLanguage) ||
    tracksToSearch.find((track) => track.languageCode.startsWith(preferredLanguage)) ||
    tracksToSearch.find((track) => track.languageCode.startsWith('en')) ||
    tracksToSearch[0];

  // Legacy timed-text remains the cheapest path and does not touch page UI. Newer
  // Gemini-generated captions can expose a valid track while returning an empty
  // timed-text body, so delegate the protected fallback to YouTube's own UI flow.
  let segments = await fetchTimedTextSegments(selectedTrack, signal);
  signal?.throwIfAborted();
  if (segments.length === 0) {
    segments = await loadTranscriptPanelSegments(videoId, selectedTrack, signal);
  }
  signal?.throwIfAborted();
  if (segments.length === 0) {
    throw new Error('Failed to retrieve transcript from YouTube');
  }
  if (currentVideoId() !== videoId) {
    throw new Error('YouTube video changed while retrieving transcript');
  }

  const transcript = {
    language: selectedTrack.languageCode,
    languageName: textFromRuns(selectedTrack.name) || selectedTrack.languageCode,
    isAutoGenerated: selectedTrack.kind === 'asr',
    segmentCount: segments.length,
  };

  if (args.format === 'text') {
    transcript.text = segments.map((segment) => segment.text).join(' ');
  } else {
    transcript.segments = segments;
  }

  return { metadata, transcript };
}

function currentVideoId() {
  return new URL(window.location.href).searchParams.get('v');
}

/**
 * Prefer the live player because it follows same-document YouTube navigation.
 * Every page-derived response is fenced to the URL's current video ID before it
 * can supply metadata, caption URLs, or transcript authority.
 */
function resolvePlayerResponse(videoId) {
  const player = document.getElementById('movie_player');
  const candidates = [];

  if (typeof player?.getPlayerResponse === 'function') {
    try {
      candidates.push(player.getPlayerResponse());
    } catch {
      // The player can exist before its API is ready; the initial response may be usable.
    }
  }
  candidates.push(window.ytInitialPlayerResponse);

  const matchingResponses = candidates.filter(
    (response) => response?.videoDetails?.videoId === videoId
  );
  const responseWithCaptions = matchingResponses.find(
    (response) => response?.captions?.playerCaptionsTracklistRenderer?.captionTracks?.length > 0
  );
  const currentResponse = responseWithCaptions || matchingResponses[0];
  if (!currentResponse) {
    throw new Error('Could not retrieve current video data from YouTube');
  }
  return currentResponse;
}

async function fetchTimedTextSegments(track, signal) {
  signal?.throwIfAborted();
  try {
    const transcriptUrl = new URL(track.baseUrl, YOUTUBE_ORIGIN);
    if (transcriptUrl.origin !== YOUTUBE_ORIGIN || transcriptUrl.pathname !== '/api/timedtext') {
      return [];
    }
    transcriptUrl.searchParams.set('fmt', 'json3');

    const response = await fetch(transcriptUrl, { credentials: 'include', signal });
    if (!response.ok) {
      return [];
    }

    const body = await response.text();
    signal?.throwIfAborted();
    if (!body.trim()) {
      return [];
    }

    return parseTimedTextJson(JSON.parse(body));
  } catch {
    signal?.throwIfAborted();
    return [];
  }
}

/**
 * YouTube's transcript endpoint now requires page-generated attestation and session
 * context. Let the site's own command load that data, then restore panel visibility,
 * rather than reading cookies or replaying opaque authorization material.
 */
async function loadTranscriptPanelSegments(videoId, selectedTrack, signal) {
  signal?.throwIfAborted();
  const selectedTrackKey = trackKey(selectedTrack);
  if (transcriptPanelLoad?.controller.signal.aborted) {
    try {
      await transcriptPanelLoad.promise;
    } catch {
      // The cancelled owner keeps the slot until its panel cleanup finishes.
    }
    signal?.throwIfAborted();
    return loadTranscriptPanelSegments(videoId, selectedTrack, signal);
  }

  const loaded = readTranscriptPanel(videoId, selectedTrack);
  if (loaded.length > 0) {
    return loaded;
  }

  if (transcriptPanelLoad) {
    if (
      transcriptPanelLoad.videoId !== videoId ||
      transcriptPanelLoad.trackKey !== selectedTrackKey
    ) {
      return [];
    }
    return consumeTranscriptPanelLoad(transcriptPanelLoad, signal);
  }

  const controller = new AbortController();
  const load = {
    videoId,
    trackKey: selectedTrackKey,
    controller,
    consumers: 0,
    promise: null,
  };
  transcriptPanelLoad = load;
  // Deferral installs the first consumer before the click can synchronously re-enter page code.
  load.promise = Promise.resolve()
    .then(() => openAndReadTranscriptPanel(videoId, selectedTrack, controller.signal))
    .finally(() => {
      if (transcriptPanelLoad === load) transcriptPanelLoad = null;
    });
  return consumeTranscriptPanelLoad(load, signal);
}

function consumeTranscriptPanelLoad(load, signal) {
  signal?.throwIfAborted();
  load.consumers += 1;

  return new Promise((resolve, reject) => {
    let settled = false;
    const finish = (callback, value, cancelled = false) => {
      if (settled) return;
      settled = true;
      signal?.removeEventListener('abort', onAbort);
      load.consumers -= 1;
      if (cancelled && load.consumers === 0 && !load.controller.signal.aborted) {
        load.controller.abort(value);
      }
      callback(value);
    };
    const onAbort = () => finish(reject, signal.reason, true);

    signal?.addEventListener('abort', onAbort, { once: true });
    load.promise.then(
      (segments) => finish(resolve, segments),
      (error) => finish(reject, error)
    );
  });
}

async function openAndReadTranscriptPanel(videoId, selectedTrack, signal) {
  signal.throwIfAborted();
  const expandedPanel = findExpandedEngagementPanel();
  if (expandedPanel && !isTranscriptPanel(expandedPanel)) {
    // Do not replace a panel the user is actively viewing.
    return [];
  }

  const openedByAgentBoard = !expandedPanel;
  let ownedPanel = expandedPanel;

  try {
    if (openedByAgentBoard) {
      const trigger = findTranscriptTrigger();
      if (!trigger || currentVideoId() !== videoId) {
        return [];
      }
      const clickable = trigger.querySelector('button, tp-yt-paper-button') || trigger;
      clickable.click();
    }

    const result = await waitForTranscriptPanel(videoId, selectedTrack, signal);
    ownedPanel = result.panel || ownedPanel;
    if (result.error) {
      throw result.error;
    }
    return result.segments;
  } catch (error) {
    if (openedByAgentBoard && signal.aborted && currentVideoId() === videoId) {
      // YouTube may apply the click after the transcript wait has already observed cancellation.
      // Keep only a short cleanup observer so the panel shell can be restored without retaining the
      // five-second data observer or transferring ownership to later UI.
      ownedPanel = ownedPanel || (await waitForOpenedTranscriptPanel(videoId));
    }
    throw error;
  } finally {
    if (openedByAgentBoard && currentVideoId() === videoId) {
      const currentPanel = findExpandedEngagementPanel();
      if (ownedPanel && currentPanel === ownedPanel && isTranscriptPanel(ownedPanel)) {
        ownedPanel.querySelector('#visibility-button button')?.click();
      }
    }
  }
}

function waitForTranscriptPanel(videoId, selectedTrack, signal) {
  return new Promise((resolve, reject) => {
    let settled = false;
    let observer;
    let timeout;
    const finish = (callback, result) => {
      if (settled) return;
      settled = true;
      if (timeout !== undefined) clearTimeout(timeout);
      observer?.disconnect();
      signal.removeEventListener('abort', onAbort);
      callback(result);
    };
    const onAbort = () => finish(reject, signal.reason);
    const check = () => {
      if (currentVideoId() !== videoId) {
        finish(resolve, { segments: [], panel: null });
        return;
      }
      const panel = findTranscriptPanelWithData(videoId);
      if (panel) {
        try {
          finish(resolve, {
            segments: readTranscriptPanel(videoId, selectedTrack, panel),
            panel,
          });
        } catch (error) {
          finish(resolve, { segments: [], panel, error });
        }
      }
    };

    if (signal.aborted) {
      reject(signal.reason);
      return;
    }
    observer = new MutationObserver(check);
    timeout = setTimeout(
      () => finish(resolve, { segments: [], panel: findExpandedEngagementPanel() }),
      TRANSCRIPT_LOAD_TIMEOUT_MS
    );
    signal.addEventListener('abort', onAbort, { once: true });
    observer.observe(document.documentElement, { childList: true, subtree: true });
    check();
  });
}

function waitForOpenedTranscriptPanel(videoId) {
  const findPanel = () => {
    if (currentVideoId() !== videoId) return null;
    const panel = findExpandedEngagementPanel();
    return panel && isTranscriptPanel(panel) ? panel : null;
  };
  const existingPanel = findPanel();
  if (existingPanel) return Promise.resolve(existingPanel);

  return new Promise((resolve) => {
    let settled = false;
    const finish = (panel) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      observer.disconnect();
      resolve(panel);
    };
    const check = () => {
      if (currentVideoId() !== videoId) {
        finish(null);
        return;
      }
      const panel = findPanel();
      if (panel) finish(panel);
    };
    const observer = new MutationObserver(check);
    const timeout = setTimeout(() => finish(null), TRANSCRIPT_CANCEL_CLEANUP_TIMEOUT_MS);
    observer.observe(document.documentElement, {
      childList: true,
      subtree: true,
      attributes: true,
    });
    check();
  });
}

function findTranscriptTrigger() {
  return Array.from(document.querySelectorAll('ytd-button-renderer')).find((element) =>
    commandTargetsTranscript(element.data?.command)
  );
}

function commandTargetsTranscript(command) {
  const seen = new WeakSet();
  let visited = 0;

  function visit(value, depth) {
    if (typeof value === 'string') {
      return value.startsWith(TRANSCRIPT_PANEL_TARGET);
    }
    if (
      value === null ||
      typeof value !== 'object' ||
      depth > 12 ||
      visited++ > 2_000 ||
      seen.has(value)
    ) {
      return false;
    }

    seen.add(value);
    return Object.values(value).some((child) => visit(child, depth + 1));
  }

  return visit(command, 0);
}

function findExpandedEngagementPanel() {
  return Array.from(document.querySelectorAll('ytd-engagement-panel-section-list-renderer')).find(
    (panel) => panel.getAttribute('visibility') === 'ENGAGEMENT_PANEL_VISIBILITY_EXPANDED'
  );
}

function isTranscriptPanel(panel) {
  return (
    panel.getAttribute('target-id')?.includes('transcript') ||
    panel.querySelector('ytd-transcript-segment-list-renderer') !== null
  );
}

function findTranscriptPanelWithData(videoId) {
  const panels = Array.from(
    document.querySelectorAll('ytd-engagement-panel-section-list-renderer')
  ).filter((panel) => panel.querySelector('ytd-transcript-segment-list-renderer'));
  const expandedPanel = findExpandedEngagementPanel();
  panels.sort((left, right) => Number(right === expandedPanel) - Number(left === expandedPanel));

  return (
    panels.find((panel) =>
      transcriptPanelItems(panel).some((item) => {
        const targetId = item?.transcriptSegmentRenderer?.targetId;
        return typeof targetId === 'string' && targetId.startsWith(\`\${videoId}.\`);
      })
    ) || null
  );
}

function readTranscriptPanel(videoId, selectedTrack, preferredPanel = null) {
  const panel = preferredPanel || findTranscriptPanelWithData(videoId);
  if (!panel) {
    return [];
  }

  const items = transcriptPanelItems(panel);
  const segments = [];
  const videoPrefix = \`\${videoId}.\`;
  const trackPrefix = \`\${videoPrefix}\${encodeTrackParams(selectedTrack)}.\`;
  let sawCurrentVideo = false;
  let sawSelectedTrack = false;

  for (const item of items) {
    const renderer = item?.transcriptSegmentRenderer;
    if (!renderer || typeof renderer.targetId !== 'string') continue;
    if (!renderer.targetId.startsWith(videoPrefix)) continue;
    sawCurrentVideo = true;
    if (!renderer.targetId.startsWith(trackPrefix)) continue;
    sawSelectedTrack = true;

    const startMs = Number(renderer.startMs);
    const endMs = Number(renderer.endMs);
    const text = textFromRuns(renderer.snippet).trim();
    if (Number.isFinite(startMs) && Number.isFinite(endMs) && text) {
      segments.push({
        start: startMs / 1000,
        duration: Math.max(0, endMs - startMs) / 1000,
        text,
      });
    }
  }

  if (sawCurrentVideo && !sawSelectedTrack) {
    throw new Error("YouTube's transcript panel opened a different caption track than requested");
  }
  return segments;
}

function transcriptPanelItems(panel) {
  const list = panel.querySelector('ytd-transcript-segment-list-renderer');
  const items = list?.data?.initialSegments;
  if (Array.isArray(items)) {
    return items;
  }

  return Array.from(list?.querySelectorAll('ytd-transcript-segment-renderer') || []).map(
    (element) => ({ transcriptSegmentRenderer: element.data })
  );
}

function encodeTrackParams(track) {
  const bytes = [];
  for (const [fieldNumber, value] of [
    [1, track.kind || ''],
    [2, track.languageCode],
    [3, track.trackName || ''],
  ]) {
    const encoded = new TextEncoder().encode(value);
    bytes.push((fieldNumber << 3) | 2, ...encodeVarint(encoded.length), ...encoded);
  }

  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return encodeURIComponent(btoa(binary));
}

function encodeVarint(value) {
  const bytes = [];
  do {
    let byte = value & 0x7f;
    value = Math.floor(value / 128);
    if (value > 0) byte |= 0x80;
    bytes.push(byte);
  } while (value > 0);
  return bytes;
}

function trackKey(track) {
  return \`\${track.kind || ''}\\u0000\${track.languageCode}\\u0000\${track.trackName || ''}\`;
}

/** Parse the legacy timed-text JSON3 representation. */
function parseTimedTextJson(data) {
  const segments = [];
  if (!Array.isArray(data?.events)) {
    return segments;
  }

  for (const event of data.events) {
    if (!Array.isArray(event.segs)) continue;

    const text = event.segs
      .map((segment) => segment.utf8 || '')
      .join('')
      .trim();
    if (!text) continue;

    segments.push({
      start: (event.tStartMs || 0) / 1000,
      duration: (event.dDurationMs || 0) / 1000,
      text,
    });
  }
  return segments;
}

function textFromRuns(value) {
  if (typeof value?.simpleText === 'string') {
    return value.simpleText;
  }
  if (Array.isArray(value?.runs)) {
    return value.runs.map((run) => run?.text || '').join('');
  }
  return '';
}
`,
};
