/**
 * Built-in Tool Sources Bundle
 *
 * This file is AUTO-GENERATED by vite-plugin-webmcp-compiler.
 * DO NOT EDIT manually - changes will be overwritten on next build.
 *
 * Contains source code for all built-in tools (system + WebMCP).
 * Used by Options UI to display read-only source code for learning/reference.
 */

export const BUILTIN_SOURCES: Record<string, string> = {
  agentboard_youtube_transcript: `'use webmcp-tool v1';

const YOUTUBE_ORIGIN = 'https://www.youtube.com';
const TRANSCRIPT_PANEL_TARGET = 'engagement-panel-searchable-transcript';
const TRANSCRIPT_LOAD_TIMEOUT_MS = 5_000;
const TRANSCRIPT_CANCEL_CLEANUP_TIMEOUT_MS = 500;

let transcriptPanelLoad = null;

export const metadata = {
  name: 'youtube_transcript',
  namespace: 'agentboard',
  version: '1.0.2',
  description:
    "Get the current YouTube video's transcript with timestamps and metadata. Retrieval may briefly open and close YouTube's transcript panel.",
  match: ['*://www.youtube.com/watch*', '*://youtube.com/watch*'],
  inputSchema: {
    type: 'object',
    properties: {
      language: {
        type: 'string',
        description:
          'Preferred language code (e.g., "en", "es"). Defaults to English or first available.',
      },
      format: {
        type: 'string',
        enum: ['segments', 'text'],
        description:
          '"segments" returns timestamped array, "text" returns concatenated plain text. Default: "segments"',
      },
    },
    additionalProperties: false,
  },
};

export async function execute(args = {}, { signal } = {}) {
  signal?.throwIfAborted();
  const videoId = currentVideoId();
  if (!videoId) {
    throw new Error('Not on a YouTube video page (no video ID found)');
  }

  const playerResponse = resolvePlayerResponse(videoId);
  const videoDetails = playerResponse.videoDetails || {};
  const metadata = {
    videoId,
    title: videoDetails.title || '',
    author: videoDetails.author || '',
    channelId: videoDetails.channelId || '',
    lengthSeconds: parseInt(videoDetails.lengthSeconds, 10) || 0,
    viewCount: parseInt(videoDetails.viewCount, 10) || 0,
    description: videoDetails.shortDescription || '',
    keywords: videoDetails.keywords || [],
    isLive: videoDetails.isLiveContent || false,
  };

  const captionTracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!captionTracks?.length) {
    return {
      metadata,
      transcript: null,
      error: 'No captions available for this video',
    };
  }

  // Prefer manual captions over auto-generated (ASR) captions.
  const manualTracks = captionTracks.filter((track) => !track.kind);
  const tracksToSearch = manualTracks.length > 0 ? manualTracks : captionTracks;
  const preferredLanguage = args.language || 'en';
  const selectedTrack =
    tracksToSearch.find((track) => track.languageCode === preferredLanguage) ||
    tracksToSearch.find((track) => track.languageCode.startsWith(preferredLanguage)) ||
    tracksToSearch.find((track) => track.languageCode.startsWith('en')) ||
    tracksToSearch[0];

  // Legacy timed-text remains the cheapest path and does not touch page UI. Newer
  // Gemini-generated captions can expose a valid track while returning an empty
  // timed-text body, so delegate the protected fallback to YouTube's own UI flow.
  let segments = await fetchTimedTextSegments(selectedTrack, signal);
  signal?.throwIfAborted();
  if (segments.length === 0) {
    segments = await loadTranscriptPanelSegments(videoId, selectedTrack, signal);
  }
  signal?.throwIfAborted();
  if (segments.length === 0) {
    throw new Error('Failed to retrieve transcript from YouTube');
  }
  if (currentVideoId() !== videoId) {
    throw new Error('YouTube video changed while retrieving transcript');
  }

  const transcript = {
    language: selectedTrack.languageCode,
    languageName: textFromRuns(selectedTrack.name) || selectedTrack.languageCode,
    isAutoGenerated: selectedTrack.kind === 'asr',
    segmentCount: segments.length,
  };

  if (args.format === 'text') {
    transcript.text = segments.map((segment) => segment.text).join(' ');
  } else {
    transcript.segments = segments;
  }

  return { metadata, transcript };
}

function currentVideoId() {
  return new URL(window.location.href).searchParams.get('v');
}

/**
 * Prefer the live player because it follows same-document YouTube navigation.
 * Every page-derived response is fenced to the URL's current video ID before it
 * can supply metadata, caption URLs, or transcript authority.
 */
function resolvePlayerResponse(videoId) {
  const player = document.getElementById('movie_player');
  const candidates = [];

  if (typeof player?.getPlayerResponse === 'function') {
    try {
      candidates.push(player.getPlayerResponse());
    } catch {
      // The player can exist before its API is ready; the initial response may be usable.
    }
  }
  candidates.push(window.ytInitialPlayerResponse);

  const matchingResponses = candidates.filter(
    (response) => response?.videoDetails?.videoId === videoId
  );
  const responseWithCaptions = matchingResponses.find(
    (response) => response?.captions?.playerCaptionsTracklistRenderer?.captionTracks?.length > 0
  );
  const currentResponse = responseWithCaptions || matchingResponses[0];
  if (!currentResponse) {
    throw new Error('Could not retrieve current video data from YouTube');
  }
  return currentResponse;
}

async function fetchTimedTextSegments(track, signal) {
  signal?.throwIfAborted();
  try {
    const transcriptUrl = new URL(track.baseUrl, YOUTUBE_ORIGIN);
    if (transcriptUrl.origin !== YOUTUBE_ORIGIN || transcriptUrl.pathname !== '/api/timedtext') {
      return [];
    }
    transcriptUrl.searchParams.set('fmt', 'json3');

    const response = await fetch(transcriptUrl, { credentials: 'include', signal });
    if (!response.ok) {
      return [];
    }

    const body = await response.text();
    signal?.throwIfAborted();
    if (!body.trim()) {
      return [];
    }

    return parseTimedTextJson(JSON.parse(body));
  } catch {
    signal?.throwIfAborted();
    return [];
  }
}

/**
 * YouTube's transcript endpoint now requires page-generated attestation and session
 * context. Let the site's own command load that data, then restore panel visibility,
 * rather than reading cookies or replaying opaque authorization material.
 */
async function loadTranscriptPanelSegments(videoId, selectedTrack, signal) {
  signal?.throwIfAborted();
  const selectedTrackKey = trackKey(selectedTrack);
  if (transcriptPanelLoad?.controller.signal.aborted) {
    try {
      await transcriptPanelLoad.promise;
    } catch {
      // The cancelled owner keeps the slot until its panel cleanup finishes.
    }
    signal?.throwIfAborted();
    return loadTranscriptPanelSegments(videoId, selectedTrack, signal);
  }

  const loaded = readTranscriptPanel(videoId, selectedTrack);
  if (loaded.length > 0) {
    return loaded;
  }

  if (transcriptPanelLoad) {
    if (
      transcriptPanelLoad.videoId !== videoId ||
      transcriptPanelLoad.trackKey !== selectedTrackKey
    ) {
      return [];
    }
    return consumeTranscriptPanelLoad(transcriptPanelLoad, signal);
  }

  const controller = new AbortController();
  const load = {
    videoId,
    trackKey: selectedTrackKey,
    controller,
    consumers: 0,
    promise: null,
  };
  transcriptPanelLoad = load;
  // Deferral installs the first consumer before the click can synchronously re-enter page code.
  load.promise = Promise.resolve()
    .then(() => openAndReadTranscriptPanel(videoId, selectedTrack, controller.signal))
    .finally(() => {
      if (transcriptPanelLoad === load) transcriptPanelLoad = null;
    });
  return consumeTranscriptPanelLoad(load, signal);
}

function consumeTranscriptPanelLoad(load, signal) {
  signal?.throwIfAborted();
  load.consumers += 1;

  return new Promise((resolve, reject) => {
    let settled = false;
    const finish = (callback, value, cancelled = false) => {
      if (settled) return;
      settled = true;
      signal?.removeEventListener('abort', onAbort);
      load.consumers -= 1;
      if (cancelled && load.consumers === 0 && !load.controller.signal.aborted) {
        load.controller.abort(value);
      }
      callback(value);
    };
    const onAbort = () => finish(reject, signal.reason, true);

    signal?.addEventListener('abort', onAbort, { once: true });
    load.promise.then(
      (segments) => finish(resolve, segments),
      (error) => finish(reject, error)
    );
  });
}

async function openAndReadTranscriptPanel(videoId, selectedTrack, signal) {
  signal.throwIfAborted();
  const expandedPanel = findExpandedEngagementPanel();
  if (expandedPanel && !isTranscriptPanel(expandedPanel)) {
    // Do not replace a panel the user is actively viewing.
    return [];
  }

  const openedByAgentBoard = !expandedPanel;
  let ownedPanel = expandedPanel;

  try {
    if (openedByAgentBoard) {
      const trigger = findTranscriptTrigger();
      if (!trigger || currentVideoId() !== videoId) {
        return [];
      }
      const clickable = trigger.querySelector('button, tp-yt-paper-button') || trigger;
      clickable.click();
    }

    const result = await waitForTranscriptPanel(videoId, selectedTrack, signal);
    ownedPanel = result.panel || ownedPanel;
    if (result.error) {
      throw result.error;
    }
    return result.segments;
  } catch (error) {
    if (openedByAgentBoard && signal.aborted && currentVideoId() === videoId) {
      // YouTube may apply the click after the transcript wait has already observed cancellation.
      // Keep only a short cleanup observer so the panel shell can be restored without retaining the
      // five-second data observer or transferring ownership to later UI.
      ownedPanel = ownedPanel || (await waitForOpenedTranscriptPanel(videoId));
    }
    throw error;
  } finally {
    if (openedByAgentBoard && currentVideoId() === videoId) {
      const currentPanel = findExpandedEngagementPanel();
      if (ownedPanel && currentPanel === ownedPanel && isTranscriptPanel(ownedPanel)) {
        ownedPanel.querySelector('#visibility-button button')?.click();
      }
    }
  }
}

function waitForTranscriptPanel(videoId, selectedTrack, signal) {
  return new Promise((resolve, reject) => {
    let settled = false;
    let observer;
    let timeout;
    const finish = (callback, result) => {
      if (settled) return;
      settled = true;
      if (timeout !== undefined) clearTimeout(timeout);
      observer?.disconnect();
      signal.removeEventListener('abort', onAbort);
      callback(result);
    };
    const onAbort = () => finish(reject, signal.reason);
    const check = () => {
      if (currentVideoId() !== videoId) {
        finish(resolve, { segments: [], panel: null });
        return;
      }
      const panel = findTranscriptPanelWithData(videoId);
      if (panel) {
        try {
          finish(resolve, {
            segments: readTranscriptPanel(videoId, selectedTrack, panel),
            panel,
          });
        } catch (error) {
          finish(resolve, { segments: [], panel, error });
        }
      }
    };

    if (signal.aborted) {
      reject(signal.reason);
      return;
    }
    observer = new MutationObserver(check);
    timeout = setTimeout(
      () => finish(resolve, { segments: [], panel: findExpandedEngagementPanel() }),
      TRANSCRIPT_LOAD_TIMEOUT_MS
    );
    signal.addEventListener('abort', onAbort, { once: true });
    observer.observe(document.documentElement, { childList: true, subtree: true });
    check();
  });
}

function waitForOpenedTranscriptPanel(videoId) {
  const findPanel = () => {
    if (currentVideoId() !== videoId) return null;
    const panel = findExpandedEngagementPanel();
    return panel && isTranscriptPanel(panel) ? panel : null;
  };
  const existingPanel = findPanel();
  if (existingPanel) return Promise.resolve(existingPanel);

  return new Promise((resolve) => {
    let settled = false;
    const finish = (panel) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      observer.disconnect();
      resolve(panel);
    };
    const check = () => {
      if (currentVideoId() !== videoId) {
        finish(null);
        return;
      }
      const panel = findPanel();
      if (panel) finish(panel);
    };
    const observer = new MutationObserver(check);
    const timeout = setTimeout(() => finish(null), TRANSCRIPT_CANCEL_CLEANUP_TIMEOUT_MS);
    observer.observe(document.documentElement, {
      childList: true,
      subtree: true,
      attributes: true,
    });
    check();
  });
}

function findTranscriptTrigger() {
  return Array.from(document.querySelectorAll('ytd-button-renderer')).find((element) =>
    commandTargetsTranscript(element.data?.command)
  );
}

function commandTargetsTranscript(command) {
  const seen = new WeakSet();
  let visited = 0;

  function visit(value, depth) {
    if (typeof value === 'string') {
      return value.startsWith(TRANSCRIPT_PANEL_TARGET);
    }
    if (
      value === null ||
      typeof value !== 'object' ||
      depth > 12 ||
      visited++ > 2_000 ||
      seen.has(value)
    ) {
      return false;
    }

    seen.add(value);
    return Object.values(value).some((child) => visit(child, depth + 1));
  }

  return visit(command, 0);
}

function findExpandedEngagementPanel() {
  return Array.from(document.querySelectorAll('ytd-engagement-panel-section-list-renderer')).find(
    (panel) => panel.getAttribute('visibility') === 'ENGAGEMENT_PANEL_VISIBILITY_EXPANDED'
  );
}

function isTranscriptPanel(panel) {
  return (
    panel.getAttribute('target-id')?.includes('transcript') ||
    panel.querySelector('ytd-transcript-segment-list-renderer') !== null
  );
}

function findTranscriptPanelWithData(videoId) {
  const panels = Array.from(
    document.querySelectorAll('ytd-engagement-panel-section-list-renderer')
  ).filter((panel) => panel.querySelector('ytd-transcript-segment-list-renderer'));
  const expandedPanel = findExpandedEngagementPanel();
  panels.sort((left, right) => Number(right === expandedPanel) - Number(left === expandedPanel));

  return (
    panels.find((panel) =>
      transcriptPanelItems(panel).some((item) => {
        const targetId = item?.transcriptSegmentRenderer?.targetId;
        return typeof targetId === 'string' && targetId.startsWith(\`\${videoId}.\`);
      })
    ) || null
  );
}

function readTranscriptPanel(videoId, selectedTrack, preferredPanel = null) {
  const panel = preferredPanel || findTranscriptPanelWithData(videoId);
  if (!panel) {
    return [];
  }

  const items = transcriptPanelItems(panel);
  const segments = [];
  const videoPrefix = \`\${videoId}.\`;
  const trackPrefix = \`\${videoPrefix}\${encodeTrackParams(selectedTrack)}.\`;
  let sawCurrentVideo = false;
  let sawSelectedTrack = false;

  for (const item of items) {
    const renderer = item?.transcriptSegmentRenderer;
    if (!renderer || typeof renderer.targetId !== 'string') continue;
    if (!renderer.targetId.startsWith(videoPrefix)) continue;
    sawCurrentVideo = true;
    if (!renderer.targetId.startsWith(trackPrefix)) continue;
    sawSelectedTrack = true;

    const startMs = Number(renderer.startMs);
    const endMs = Number(renderer.endMs);
    const text = textFromRuns(renderer.snippet).trim();
    if (Number.isFinite(startMs) && Number.isFinite(endMs) && text) {
      segments.push({
        start: startMs / 1000,
        duration: Math.max(0, endMs - startMs) / 1000,
        text,
      });
    }
  }

  if (sawCurrentVideo && !sawSelectedTrack) {
    throw new Error("YouTube's transcript panel opened a different caption track than requested");
  }
  return segments;
}

function transcriptPanelItems(panel) {
  const list = panel.querySelector('ytd-transcript-segment-list-renderer');
  const items = list?.data?.initialSegments;
  if (Array.isArray(items)) {
    return items;
  }

  return Array.from(list?.querySelectorAll('ytd-transcript-segment-renderer') || []).map(
    (element) => ({ transcriptSegmentRenderer: element.data })
  );
}

function encodeTrackParams(track) {
  const bytes = [];
  for (const [fieldNumber, value] of [
    [1, track.kind || ''],
    [2, track.languageCode],
    [3, track.trackName || ''],
  ]) {
    const encoded = new TextEncoder().encode(value);
    bytes.push((fieldNumber << 3) | 2, ...encodeVarint(encoded.length), ...encoded);
  }

  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return encodeURIComponent(btoa(binary));
}

function encodeVarint(value) {
  const bytes = [];
  do {
    let byte = value & 0x7f;
    value = Math.floor(value / 128);
    if (value > 0) byte |= 0x80;
    bytes.push(byte);
  } while (value > 0);
  return bytes;
}

function trackKey(track) {
  return \`\${track.kind || ''}\\u0000\${track.languageCode}\\u0000\${track.trackName || ''}\`;
}

/** Parse the legacy timed-text JSON3 representation. */
function parseTimedTextJson(data) {
  const segments = [];
  if (!Array.isArray(data?.events)) {
    return segments;
  }

  for (const event of data.events) {
    if (!Array.isArray(event.segs)) continue;

    const text = event.segs
      .map((segment) => segment.utf8 || '')
      .join('')
      .trim();
    if (!text) continue;

    segments.push({
      start: (event.tStartMs || 0) / 1000,
      duration: (event.dDurationMs || 0) / 1000,
      text,
    });
  }
  return segments;
}

function textFromRuns(value) {
  if (typeof value?.simpleText === 'string') {
    return value.simpleText;
  }
  if (Array.isArray(value?.runs)) {
    return value.runs.map((run) => run?.text || '').join('');
  }
  return '';
}
`,
  agentboard_fetch_url: `/**
 * System Tool: URL Fetch for LLM Research
 *
 * Executes in background service worker to avoid CORS restrictions.
 * Returns structured HTTP status metadata with raw content or optional markdown extraction.
 *
 * Pre-converted to AI SDK format for direct use in tool registry.
 */

import { raceWithAbort } from '../../../abort';
import log from '../../../logger';
import { ConfigStorage } from '../../../storage/config';
import { convertToMarkdown } from './content-extractor';
import { tool } from 'ai';
import { z } from 'zod';

export const FETCH_URL_TOOL_NAME = 'agentboard_fetch_url';
const TOOL_VERSION = '1.0.0';
const TOOL_DESCRIPTION =
  'Fetch content from external URLs. For the current page, prefer site-specific tools instead. ' +
  'Returns a structured result with HTTP status metadata plus raw content, or clean markdown when requested. ' +
  'Non-2xx responses still return any available content.';

const PARAM_DESCRIPTIONS = {
  url: 'URL to fetch (supports HTTPS URLs, including private IPs, and HTTP localhost URLs)',
  convertToMarkdown:
    'Convert HTML content to markdown format with metadata (default: false). ' +
    'Extracts article content, strips ads/navigation, formats as clean markdown.',
} as const;

/**
 * Zod schema for fetch URL arguments
 * Descriptions are imported from PARAM_DESCRIPTIONS to avoid duplication
 */
const fetchUrlSchema = z.object({
  url: z.string().describe(PARAM_DESCRIPTIONS.url),
  convertToMarkdown: z.boolean().optional().describe(PARAM_DESCRIPTIONS.convertToMarkdown),
});

export const fetchUrlOutputSchema = z.object({
  status: z.number().int().min(0).max(999).describe('HTTP response status code'),
  statusText: z.string().optional().describe('HTTP response reason phrase when available'),
  content: z.string().describe('Raw response body or extracted markdown'),
});

export type FetchUrlResult = z.infer<typeof fetchUrlOutputSchema>;

/**
 * Execute fetch URL operation
 */
async function executeFetchUrl(
  args: z.infer<typeof fetchUrlSchema>,
  { abortSignal }: { abortSignal?: AbortSignal } = {}
): Promise<FetchUrlResult> {
  const { url, convertToMarkdown: shouldConvert } = args;

  log.debug('[fetch_url] Fetching', {
    convertToMarkdown: shouldConvert,
  });

  try {
    const isEnabled = await raceWithAbort(
      ConfigStorage.getInstance().isBuiltinToolEnabled(FETCH_URL_TOOL_NAME),
      abortSignal
    );
    if (!isEnabled) throw new Error('Tool disabled');

    // Match manifest host permissions instead of promising fetches Chromium will reject.
    const parsedUrl = new URL(url);
    if (
      parsedUrl.protocol !== 'https:' &&
      !(parsedUrl.protocol === 'http:' && parsedUrl.hostname === 'localhost')
    ) {
      throw new Error('Unsupported URL');
    }

    // Get version from manifest dynamically (falls back for tests)
    const version =
      typeof chrome !== 'undefined' && chrome.runtime?.getManifest
        ? chrome.runtime.getManifest().version
        : '0.1.0';

    // Model-selected URLs are never allowed to inherit browser session credentials.
    const response = await globalThis.fetch(url, {
      credentials: 'omit',
      signal: abortSignal,
      headers: {
        'User-Agent': \`AgentBoard/\${version}\`,
      },
    });

    // A completed HTTP response is evidence, even when its status is non-2xx.
    abortSignal?.throwIfAborted();
    const content = await raceWithAbort(response.text(), abortSignal);
    abortSignal?.throwIfAborted();

    log.debug('[fetch_url] Fetched', content.length, 'bytes');

    let result = content;
    if (shouldConvert && content.length > 0) {
      log.debug('[fetch_url] Converting to markdown');
      result = convertToMarkdown(content, { url });
      log.debug('[fetch_url] Converted to', result.length, 'characters');
    }

    abortSignal?.throwIfAborted();
    const statusText = response.statusText.trim();
    return {
      status: response.status,
      ...(statusText && { statusText }),
      content: result,
    };
  } catch {
    log.error('[fetch_url] Request failed');
    throw new Error('URL fetch failed');
  }
}

/**
 * Fetch URL tool - pre-converted to AI SDK format
 * Ready for direct registration in tool registry
 */
export const fetchUrlTool = tool({
  description: TOOL_DESCRIPTION,
  inputSchema: fetchUrlSchema,
  outputSchema: fetchUrlOutputSchema,
  execute: executeFetchUrl,
});

/**
 * Tool metadata for display purposes (Options UI)
 * References the same constants as the tool definition above
 */
export const FETCH_URL_METADATA = {
  description: TOOL_DESCRIPTION,
  version: TOOL_VERSION,
  inputSchema: {
    type: 'object',
    properties: {
      url: {
        type: 'string',
        description: PARAM_DESCRIPTIONS.url,
      },
      convertToMarkdown: {
        type: 'boolean',
        description: PARAM_DESCRIPTIONS.convertToMarkdown,
      },
    },
    required: ['url'],
  },
};

/**
 * Export execute function for testing
 */
export { executeFetchUrl };
`,
  agentboard_navigate: `/**
 * System Tool: Tab Navigation
 *
 * Executes in background service worker using chrome.tabs.update().
 * Waits for full page load (onCompleted) before returning.
 *
 * Design: Factory pattern because the tool needs a tabId that's only known
 * at stream time. ToolRegistry registers the factory globally and materializes
 * a tab-bound tool for each stream.
 *
 * Lifecycle sequence:
 * 1. chrome.tabs.update(tabId, { url })
 * 2. onBeforeNavigate fires → old tools cleared → toolsInvalidated flag set
 * 3. waitForNavigation waits for onCompleted
 * 4. Tool returns result (step finishes)
 * 5. stopWhen detects toolsInvalidated → stream stops
 * 6. Sidebar auto-continues with fresh tools from new page
 */

import { raceWithAbort } from '../../../abort';
import log from '../../../logger';
import { ConfigStorage } from '../../../storage/config';
import { getTabManager } from '../../lifecycle';
import { tool } from 'ai';
import { z } from 'zod';

export const NAVIGATE_TOOL_NAME = 'agentboard_navigate';
const TOOL_VERSION = '1.0.0';
const TOOL_DESCRIPTION =
  'Navigate the current browser tab to a URL and wait for the page to load. ' +
  'After navigation, available tools may change. Use the appropriate tool to acquire context from the new page.';

const PARAM_DESCRIPTIONS = {
  url: 'The URL to navigate to. Must be a full valid URL (e.g., https://example.com).',
} as const;

const navigateSchema = z.object({
  url: z.string().describe(PARAM_DESCRIPTIONS.url),
});

/**
 * Create a navigate tool bound to a specific tab.
 * Returns an AI SDK tool with the tabId captured in its execute closure.
 */
export function createNavigateTool(tabId: number) {
  return tool({
    description: TOOL_DESCRIPTION,
    inputSchema: navigateSchema,
    execute: async (args, { abortSignal }: { abortSignal?: AbortSignal } = {}) => {
      const { url } = args;
      log.info(\`[navigate] Navigating tab \${tabId} to \${url}\`);

      const isEnabled = await raceWithAbort(
        ConfigStorage.getInstance().isBuiltinToolEnabled(NAVIGATE_TOOL_NAME),
        abortSignal
      );
      if (!isEnabled) throw new Error('Tool disabled');

      // Validate URL — only allow http/https to prevent dangerous schemes
      // (javascript:, data:, file://, chrome-extension:// etc.)
      const parsed = new URL(url); // throws on invalid
      if (!['http:', 'https:'].includes(parsed.protocol)) {
        throw new Error(\`Only http and https URLs are supported. Got: \${parsed.protocol}\`);
      }

      // Register navigation listener BEFORE triggering navigation.
      // chrome.tabs.update resolves when the tab object updates, not when
      // navigation completes. For fast navigations (cached, hash change),
      // onCompleted can fire before the next microtask — registering after
      // would miss the event entirely.
      const tabManager = getTabManager();
      const navigationController = new AbortController();
      const abortNavigation = () => navigationController.abort();
      if (abortSignal?.aborted) abortNavigation();
      else abortSignal?.addEventListener('abort', abortNavigation, { once: true });

      try {
        const navigationPromise = tabManager.waitForNavigation(
          tabId,
          30000,
          navigationController.signal
        );

        const [, result] = await Promise.all([
          raceWithAbort(chrome.tabs.update(tabId, { url }), abortSignal),
          navigationPromise,
        ]);

        const tab = await raceWithAbort(chrome.tabs.get(tabId), abortSignal);
        const summary = \`Navigated to \${result.url}\${tab.title ? \` — "\${tab.title}"\` : ''}\`;
        log.info(\`[navigate] \${summary}\`);
        return summary;
      } finally {
        abortSignal?.removeEventListener('abort', abortNavigation);
        // A failed tabs.update must not leave the navigation timer/listeners alive.
        abortNavigation();
      }
    },
  });
}

/**
 * Tool metadata for display in Options UI.
 * Matches the shape used by fetch_url's FETCH_URL_METADATA.
 */
export const NAVIGATE_TOOL_METADATA = {
  description: TOOL_DESCRIPTION,
  version: TOOL_VERSION,
  inputSchema: {
    type: 'object',
    properties: {
      url: {
        type: 'string',
        description: PARAM_DESCRIPTIONS.url,
      },
    },
    required: ['url'],
  },
};
`,
  agentboard_read_page: `import { tool } from 'ai';
import { z } from 'zod';
import { ConfigStorage } from '../../../storage/config';
import { getTabManager } from '../../lifecycle';
import { withAbortReason } from './abort';
import { readHtmlDocument } from './html-runner';
import {
  READ_PAGE_DESCRIPTION,
  READ_PAGE_PARAMETER_DESCRIPTIONS,
  READ_PAGE_TOOL_NAME,
} from './metadata';
import {
  PDF_DEFAULT_MAX_LENGTH,
  PDF_DEFAULT_MAX_PAGES,
  PDF_HARD_MAX_LENGTH,
  PDF_HARD_MAX_PAGES,
  PDF_MIN_MAX_LENGTH,
  type PdfFailure,
  type PdfReadOptions,
} from './pdf/protocol';
import { readPdfDocument } from './pdf/reader';

export { READ_PAGE_TOOL_NAME } from './metadata';

const DOCUMENT_TYPE_PROBE_TIMEOUT_MS = 10_000;
const READABLE_DOCUMENT_CONTENT_TYPES = new Set([
  'text/html',
  'application/xhtml+xml',
  'application/pdf',
]);

const readPageSchema = z
  .object({
    maxLength: z
      .number()
      .min(PDF_MIN_MAX_LENGTH)
      .max(PDF_HARD_MAX_LENGTH)
      .optional()
      .describe(READ_PAGE_PARAMETER_DESCRIPTIONS.maxLength),
    startPage: z
      .number()
      .int()
      .min(1)
      .optional()
      .describe(READ_PAGE_PARAMETER_DESCRIPTIONS.startPage),
    maxPages: z
      .number()
      .int()
      .min(1)
      .max(PDF_HARD_MAX_PAGES)
      .optional()
      .describe(READ_PAGE_PARAMETER_DESCRIPTIONS.maxPages),
  })
  .strict();

export type ReadPageInput = z.infer<typeof readPageSchema>;

function failure(code: PdfFailure['error']['code'], message: string): PdfFailure {
  return { success: false, error: { code, message } };
}

function normalizeOptions(input: ReadPageInput): PdfReadOptions {
  return {
    // HTML historically accepts fractional numbers and floors them; keep one public schema while
    // normalizing the PDF worker's integer-only control plane at this boundary.
    maxLength: Math.floor(input.maxLength ?? PDF_DEFAULT_MAX_LENGTH),
    startPage: input.startPage ?? 1,
    maxPages: input.maxPages ?? PDF_DEFAULT_MAX_PAGES,
  };
}

async function probeContentType(tabId: number, documentId: string): Promise<string> {
  const results = await chrome.scripting.executeScript({
    target: { tabId, documentIds: [documentId] },
    world: 'ISOLATED',
    func: () => document.contentType,
  });
  const result = results.length === 1 ? results[0] : undefined;
  if (!result || result.documentId !== documentId || result.frameId !== 0) {
    throw new Error('Document route changed');
  }
  if (typeof result.result !== 'string') {
    throw new Error('Document content type is unavailable');
  }
  const contentType = result.result.trim().toLowerCase();
  if (!READABLE_DOCUMENT_CONTENT_TYPES.has(contentType)) {
    throw new Error('Document content type is unsupported');
  }
  return contentType;
}

async function detectDocumentType(
  tabId: number,
  documentId: string,
  abortSignal?: AbortSignal
): Promise<{ contentType?: string; failure?: PdfFailure }> {
  const probe = new AbortController();
  let timedOut = false;
  const onCallerAbort = () => probe.abort(abortSignal?.reason);
  abortSignal?.addEventListener('abort', onCallerAbort, { once: true });
  const timeout = setTimeout(() => {
    timedOut = true;
    probe.abort(new DOMException('Document type probe timed out', 'TimeoutError'));
  }, DOCUMENT_TYPE_PROBE_TIMEOUT_MS);

  try {
    return {
      contentType: await withAbortReason(probeContentType(tabId, documentId), probe.signal),
    };
  } catch {
    if (abortSignal?.aborted) throw abortSignal.reason;
    if (timedOut) {
      return { failure: failure('TIMEOUT', 'Document type detection exceeded its time limit.') };
    }
    return {
      failure: getTabManager().ownsDocument(tabId, documentId)
        ? failure('PARSE_FAILED', 'The document type could not be determined.')
        : failure('NAVIGATED', 'The document route was replaced before it could be read.'),
    };
  } finally {
    clearTimeout(timeout);
    abortSignal?.removeEventListener('abort', onCallerAbort);
  }
}

/**
 * One extension-owned document reader chooses its HTML or PDF implementation from browser-owned
 * content type. The model-facing registry remains independent of page-reported tool descriptors.
 */
export function createReadPageTool(tabId: number) {
  return tool({
    description: READ_PAGE_DESCRIPTION,
    inputSchema: readPageSchema,
    execute: async (untrustedInput, { abortSignal }: { abortSignal?: AbortSignal } = {}) => {
      const parsed = readPageSchema.safeParse(untrustedInput === undefined ? {} : untrustedInput);
      if (!parsed.success) throw new Error('WebMCP tool arguments are invalid');
      if (abortSignal?.aborted) throw abortSignal.reason;

      const isEnabled = await withAbortReason(
        ConfigStorage.getInstance().isBuiltinToolEnabled(READ_PAGE_TOOL_NAME),
        abortSignal
      );
      if (!isEnabled) throw new Error('Tool disabled');

      const tabManager = getTabManager();
      const route = tabManager.getOwnedDocument(tabId);
      if (!route) throw new Error('The read-page document route is unavailable.');

      const detected = await detectDocumentType(tabId, route.documentId, abortSignal);
      if (detected.failure) return detected.failure;

      if (detected.contentType !== 'application/pdf') {
        const htmlInput =
          parsed.data.maxLength === undefined ? {} : { maxLength: parsed.data.maxLength };
        try {
          const result = await readHtmlDocument(tabId, route.documentId, htmlInput, abortSignal);
          if (!tabManager.ownsDocument(tabId, route.documentId)) {
            return failure('NAVIGATED', 'The HTML document route was replaced before settlement.');
          }
          return result;
        } catch (error) {
          if (!tabManager.ownsDocument(tabId, route.documentId)) {
            return failure('NAVIGATED', 'The HTML document route was replaced before settlement.');
          }
          if (error instanceof DOMException && error.name === 'TimeoutError') {
            return failure('TIMEOUT', 'HTML extraction exceeded its time limit.');
          }
          throw error;
        }
      }

      const result = await readPdfDocument(
        tabId,
        route.documentId,
        normalizeOptions(parsed.data),
        abortSignal
      );
      if (!tabManager.ownsDocument(tabId, route.documentId)) {
        return failure('NAVIGATED', 'The PDF document route was replaced before settlement.');
      }
      return result;
    },
  });
}
`,
};
